name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Haxe environment
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.0

      - name: Setup Haxe dependencies
        run: |
          haxelib install utest
          haxelib install iterators
          haxelib install haxe-strings
          haxelib install safety

      - name: Run tests
        run: haxe test.hxml
